#!/bin/bash

# 초기 워크스페이스 출력
hyprctl activeworkspace -j | jq -r '.id'

# 이벤트 모니터링 (모든 워크스페이스 관련 이벤트)
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  case $line in
    workspace*)
      hyprctl activeworkspace -j | jq -r '.id'
      ;;
  esac
done
