#!/bin/bash

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"
  EWW_BIN="/usr/bin/eww"

  run() {
    # Check if HDMI-A-1 monitor is connected
    if hyprctl monitors | grep -q "HDMI-A-1"; then
      ${EWW_BIN} -c $HOME/.config/eww open calendar
    else
      ${EWW_BIN} -c $HOME/.config/eww open calendar_fallback
    fi
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww close system system_fallback music_win music_win_fallback audio_ctl audio_ctl_fallback
    touch "$LOCK_FILE"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww close calendar calendar_fallback
    rm "$LOCK_FILE" && echo "closed"
  fi
}

system() {
  LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"
  EWW_BIN="/usr/bin/eww"

  run() {
    # Check if HDMI-A-1 monitor is connected
    if hyprctl monitors | grep -q "HDMI-A-1"; then
      ${EWW_BIN} -c $HOME/.config/eww open system
    else
      ${EWW_BIN} -c $HOME/.config/eww open system_fallback
    fi
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww close calendar calendar_fallback music_win music_win_fallback audio_ctl audio_ctl_fallback
    touch "$LOCK_FILE_MEM"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww close system system_fallback
    rm "$LOCK_FILE_MEM" && echo "closed"
  fi
}

music() {
  LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"
  EWW_BIN="/usr/bin/eww"

  run() {
    # Check if HDMI-A-1 monitor is connected
    if hyprctl monitors | grep -q "HDMI-A-1"; then
      ${EWW_BIN} -c $HOME/.config/eww open music_win
    else
      ${EWW_BIN} -c $HOME/.config/eww open music_win_fallback
    fi
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_SONG" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww close system system_fallback calendar calendar_fallback audio_ctl audio_ctl_fallback
    touch "$LOCK_FILE_SONG"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww close music_win music_win_fallback
    rm "$LOCK_FILE_SONG" && echo "closed"
  fi
}

audio() {
  LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"
  EWW_BIN="/usr/bin/eww"

  run() {
    # Check if HDMI-A-1 monitor is connected
    if hyprctl monitors | grep -q "HDMI-A-1"; then
      ${EWW_BIN} -c $HOME/.config/eww open audio_ctl
    else
      ${EWW_BIN} -c $HOME/.config/eww open audio_ctl
    fi
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww close system system_fallback calendar calendar_fallback music_win music_win_fallback
    touch "$LOCK_FILE_AUDIO"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww close audio_ctl audio_ctl_fallback
    rm "$LOCK_FILE_AUDIO" && echo "closed"
  fi
}

if [ "$1" = "calendar" ]; then
  calendar
elif [ "$1" = "system" ]; then
  system
elif [ "$1" = "music" ]; then
  music
elif [ "$1" = "audio" ]; then
  audio
fi
