#!/bin/bash

workspaces() {
    # Get all workspaces
    WORKSPACES=$(hyprctl workspaces -j | jq -r '.[] | .id' | sort -n)

    # Get active workspace
    ACTIVE=$(hyprctl activeworkspace -j | jq -r '.id')

    ws1="1"
    ws2="2"
    ws3="3"
    ws4="4"
    ws5="5"
    ws6="6"

    # Check if workspaces exist and are occupied
    o1=""
    o2=""
    o3=""
    o4=""
    o5=""
    o6=""

    f1=""
    f2=""
    f3=""
    f4=""
    f5=""
    f6=""

    # Check occupied workspaces
    for ws in $WORKSPACES; do
        case $ws in
            1) o1="1" ;;
            2) o2="2" ;;
            3) o3="3" ;;
            4) o4="4" ;;
            5) o5="5" ;;
            6) o6="6" ;;
        esac
    done

    # Check active workspace
    case $ACTIVE in
        1) f1="1" ;;
        2) f2="2" ;;
        3) f3="3" ;;
        4) f4="4" ;;
        5) f5="5" ;;
        6) f6="6" ;;
    esac

    # Set icons
    ic_1="1"
    ic_2="2"
    ic_3="3"
    ic_4="4"
    ic_5="5"
    ic_6="6"

    echo "(box :class \"works\" :orientation \"h\" :spacing 5 (button :onclick \"hyprctl dispatch workspace $ws1\" :class \"0$o1$f1\" \"$ic_1\") (button :onclick \"hyprctl dispatch workspace $ws2\" :class \"0$o2$f2\" \"$ic_2\") (button :onclick \"hyprctl dispatch workspace $ws3\" :class \"0$o3$f3\" \"$ic_3\") (button :onclick \"hyprctl dispatch workspace $ws4\" :class \"0$o4$f4\" \"$ic_4\") (button :onclick \"hyprctl dispatch workspace $ws5\" :class \"0$o5$f5\" \"$ic_5\") (button :onclick \"hyprctl dispatch workspace $ws6\" :class \"0$o6$f6\" \"$ic_6\"))"
}

workspaces

# Listen for workspace changes
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    case $line in
        workspace*|createworkspace*|destroyworkspace*)
            workspaces
            ;;
    esac
done